# Generated by Django 3.2.8 on 2022-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cart_name', models.CharField(default='Cart 1', max_length=200)),
                ('Total_Items', models.PositiveIntegerField(default=0)),
                ('Bill_Total', models.PositiveIntegerField(default=0)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
