# Generated by Django 3.2.8 on 2022-02-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('bill_total', models.PositiveIntegerField(default=0)),
                ('transactionDateTime', models.DateTimeField(auto_now_add=True)),
                ('payment_done', models.BooleanField(default=False)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
